version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
